### ISSUE TITLE
AuthenticationError 401

### ISSUE THREAD

**Issue by DrBinary9** [DrBinary9/imagine#1]
AuthenticationError: 401 {"error":{"message":"Invalid API Key","type":"invalid_request_error","code":"invalid_api_key"}}
    at APIError.generate (/home/ryan/Desktop/best-projects/imagine/node_modules/groq-sdk/error.js:43:20)
    at Groq.makeStatusError (/home/ryan/Desktop/best-projects/imagine/node_modules/groq-sdk/core.js:275:33)
    at Groq.makeRequest (/home/ryan/Desktop/best-projects/imagine/node_modules/groq-sdk/core.js:318:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getGroqChatCompletion (/home/ryan/Desktop/best-projects/imagine/backend/server.js:19:20)
    at async /home/ryan/Desktop/best-projects/imagine/backend/server.js:47:22 {
  status: 401,
  headers: {
    'alt-svc': 'h3=":443"; ma=86400',
    'cache-control': 'private, max-age=0, no-store, no-cache, must-revalidate',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '8d515dca59ae3fa8-BOM',
    connection: 'keep-alive',
    'content-length': '96',
    'content-type': 'application/json',
    date: 'Sat, 19 Oct 2024 14:13:01 GMT',
    server: 'cloudflare',
    'set-cookie': '__cf_bm=mCNHFx.9wIxXFIOpqHFitWndWmFa3McBvVvYp7PyacA-1729347181-1.0.1.1-D0v6eJB.pnaeI7WDOuJI3QistNtCh3AAOv_vko93b_lQ7rQxj3mbvlIl97iPqp4BBSlSKVr_8uu.zxLWPNkkdg; path=/; expires=Sat, 19-Oct-24 14:43:01 GMT; domain=.groq.com; HttpOnly; Secure; SameSite=None',
    vary: 'Origin',
    via: '1.1 google',
    'x-request-id': 'req_01jajhzpqze1kbanhd8r26z0zd'
  },
  error: {
    error: {
      message: 'Invalid API Key',
      type: 'invalid_request_error',
      code: 'invalid_api_key'
    }
  }
}
The server raises this error. How to resolve this?

**Comment by DrBinary9** [comment]
Add the key in the .env file. GROQ_API_KEY = 'your_key'
